// Generated by Apple Swift version 5.0 (swiftlang-1001.0.69.5 clang-1001.0.46.3)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#include <Foundation/Foundation.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...)
# endif
#endif

#if __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if __has_attribute(swift_name)
# define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
#else
# define SWIFT_COMPILE_NAME(X)
#endif
#if __has_attribute(objc_method_family)
# define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
#else
# define SWIFT_METHOD_FAMILY(X)
#endif
#if __has_attribute(noescape)
# define SWIFT_NOESCAPE __attribute__((noescape))
#else
# define SWIFT_NOESCAPE
#endif
#if __has_attribute(warn_unused_result)
# define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
#else
# define SWIFT_WARN_UNUSED_RESULT
#endif
#if __has_attribute(noreturn)
# define SWIFT_NORETURN __attribute__((noreturn))
#else
# define SWIFT_NORETURN
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if defined(__has_attribute) && __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility)
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if __has_feature(attribute_diagnose_if_objc)
# define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
#else
# define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
#endif
#if __has_feature(modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import CocoaMQTT;
@import CoreGraphics;
@import Foundation;
@import ObjectiveC;
@import RealmSwift;
@import Security;
@import SlackTextViewController;
@import UIKit;
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="MQTTSDK",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

@class UIWindow;
@class UIApplication;

SWIFT_CLASS("_TtC7MQTTSDK11AppDelegate")
@interface AppDelegate : UIResponder <UIApplicationDelegate>
@property (nonatomic, strong) UIWindow * _Nullable window;
- (BOOL)application:(UIApplication * _Nonnull)application didFinishLaunchingWithOptions:(NSDictionary<UIApplicationLaunchOptionsKey, id> * _Nullable)launchOptions SWIFT_WARN_UNUSED_RESULT;
- (void)applicationWillResignActive:(UIApplication * _Nonnull)application;
- (void)applicationDidEnterBackground:(UIApplication * _Nonnull)application;
- (void)applicationWillEnterForeground:(UIApplication * _Nonnull)application;
- (void)applicationDidBecomeActive:(UIApplication * _Nonnull)application;
- (void)applicationWillTerminate:(UIApplication * _Nonnull)application;
- (void)application:(UIApplication * _Nonnull)application didReceiveRemoteNotification:(NSDictionary * _Nonnull)userInfo;
- (void)application:(UIApplication * _Nonnull)application didReceiveRemoteNotification:(NSDictionary * _Nonnull)userInfo fetchCompletionHandler:(void (^ _Nonnull)(UIBackgroundFetchResult))completionHandler;
- (void)application:(UIApplication * _Nonnull)application didRegisterForRemoteNotificationsWithDeviceToken:(NSData * _Nonnull)deviceToken;
- (void)application:(UIApplication * _Nonnull)application didFailToRegisterForRemoteNotificationsWithError:(NSError * _Nonnull)error;
- (void)reachabilityChangedWithNote:(NSNotification * _Nonnull)note;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end



@class RLMRealm;
@class RLMObjectSchema;
@class RLMSchema;

SWIFT_CLASS("_TtC7MQTTSDK9BaseModel")
@interface BaseModel : RealmSwiftObject
@property (nonatomic, copy) NSString * _Nullable identifier;
+ (NSString * _Nullable)primaryKey SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithRealm:(RLMRealm * _Nonnull)realm schema:(RLMObjectSchema * _Nonnull)schema OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithValue:(id _Nonnull)value schema:(RLMSchema * _Nonnull)schema OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC7MQTTSDK10Attachment")
@interface Attachment : BaseModel
@property (nonatomic) BOOL collapsed;
@property (nonatomic, copy) NSString * _Nullable text;
@property (nonatomic, copy) NSString * _Nullable thumbURL;
@property (nonatomic, copy) NSString * _Nullable color;
@property (nonatomic, copy) NSString * _Nonnull title;
@property (nonatomic, copy) NSString * _Nonnull titleLink;
@property (nonatomic) BOOL titleLinkDownload;
@property (nonatomic, copy) NSString * _Nullable imageURL;
@property (nonatomic, copy) NSString * _Nullable imageType;
@property (nonatomic) NSInteger imageSize;
@property (nonatomic, copy) NSString * _Nullable imageDescription;
@property (nonatomic, copy) NSString * _Nullable audioURL;
@property (nonatomic, copy) NSString * _Nullable audioType;
@property (nonatomic) NSInteger audioSize;
@property (nonatomic, copy) NSString * _Nullable videoURL;
@property (nonatomic, copy) NSString * _Nullable videoType;
@property (nonatomic) NSInteger videoSize;
+ (NSArray<NSString *> * _Nonnull)ignoredProperties SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithRealm:(RLMRealm * _Nonnull)realm schema:(RLMObjectSchema * _Nonnull)schema OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithValue:(id _Nonnull)value schema:(RLMSchema * _Nonnull)schema OBJC_DESIGNATED_INITIALIZER;
@end





@class AuthSettings;

SWIFT_CLASS("_TtC7MQTTSDK4Auth")
@interface Auth : RealmSwiftObject
@property (nonatomic, copy) NSString * _Nonnull serverURL;
@property (nonatomic, strong) AuthSettings * _Nullable settings;
@property (nonatomic, copy) NSString * _Nullable token;
@property (nonatomic, copy) NSDate * _Nullable tokenExpires;
@property (nonatomic, copy) NSDate * _Nullable lastAccess;
@property (nonatomic, copy) NSDate * _Nullable lastSubscriptionFetch;
@property (nonatomic, copy) NSString * _Nullable userId;
+ (NSString * _Nullable)primaryKey SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithRealm:(RLMRealm * _Nonnull)realm schema:(RLMObjectSchema * _Nonnull)schema OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithValue:(id _Nonnull)value schema:(RLMSchema * _Nonnull)schema OBJC_DESIGNATED_INITIALIZER;
@end




SWIFT_CLASS("_TtC7MQTTSDK12AuthSettings")
@interface AuthSettings : BaseModel
@property (nonatomic, copy) NSString * _Nullable siteURL;
@property (nonatomic, copy) NSString * _Nullable cdnPrefixURL;
@property (nonatomic, copy) NSString * _Nullable serverName;
@property (nonatomic, copy) NSString * _Nullable serverFaviconURL;
@property (nonatomic) BOOL useUserRealName;
@property (nonatomic) BOOL allowSpecialCharsOnRoomNames;
@property (nonatomic) BOOL favoriteRooms;
@property (nonatomic) BOOL isUsernameEmailAuthenticationEnabled;
@property (nonatomic) BOOL isGoogleAuthenticationEnabled;
@property (nonatomic) BOOL isLDAPAuthenticationEnabled;
@property (nonatomic, copy) NSString * _Nullable rawRegistrationForm;
@property (nonatomic, copy) NSString * _Nullable uploadStorageType;
@property (nonatomic) BOOL hideMessageUserJoined;
@property (nonatomic) BOOL hideMessageUserLeft;
@property (nonatomic) BOOL hideMessageUserAdded;
@property (nonatomic) BOOL hideMessageUserMutedUnmuted;
@property (nonatomic) BOOL hideMessageUserRemoved;
@property (nonatomic, copy) NSString * _Nullable rawCustomFields;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithRealm:(RLMRealm * _Nonnull)realm schema:(RLMObjectSchema * _Nonnull)schema OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithValue:(id _Nonnull)value schema:(RLMSchema * _Nonnull)schema OBJC_DESIGNATED_INITIALIZER;
@end





SWIFT_CLASS("_TtC7MQTTSDK7Channel")
@interface Channel : BaseModel
@property (nonatomic, copy) NSString * _Nullable name;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithRealm:(RLMRealm * _Nonnull)realm schema:(RLMObjectSchema * _Nonnull)schema OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithValue:(id _Nonnull)value schema:(RLMSchema * _Nonnull)schema OBJC_DESIGNATED_INITIALIZER;
@end



@class UICollectionViewLayoutAttributes;
@class UICollectionViewUpdateItem;
@class NSCoder;

SWIFT_CLASS("_TtC7MQTTSDK28ChatCollectionViewFlowLayout")
@interface ChatCollectionViewFlowLayout : UICollectionViewFlowLayout
- (NSArray<UICollectionViewLayoutAttributes *> * _Nullable)layoutAttributesForElementsInRect:(CGRect)rect SWIFT_WARN_UNUSED_RESULT;
- (void)prepareForCollectionViewUpdates:(NSArray<UICollectionViewUpdateItem *> * _Nonnull)updateItems;
- (void)finalizeCollectionViewUpdates;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC7MQTTSDK7ChatDAO")
@interface ChatDAO : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class UIView;
@class UILabel;
@class UITableView;
@class UITableViewCell;
@class UICollectionViewLayout;
@class UIScrollView;
@class NSBundle;

SWIFT_CLASS("_TtC7MQTTSDK13ChatMessageVC")
@interface ChatMessageVC : SLKTextViewController
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified viewNoDataFound;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified lblNoLabel;
@property (nonatomic, readonly, strong) UITableView * _Nonnull tableView;
+ (UITableViewStyle)tableViewStyleForCoder:(NSCoder * _Nonnull)decoder SWIFT_WARN_UNUSED_RESULT;
- (void)viewDidLoad;
- (void)NotificationIdentifierReceiveMSGWithNotification:(NSNotification * _Nonnull)notification;
- (void)viewDidLayoutSubviews;
- (void)viewWillAppear:(BOOL)animated;
- (void)hideKeyboard;
- (NSInteger)tableView:(UITableView * _Nonnull)tableView numberOfRowsInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (void)dismissAlert;
- (CGFloat)tableView:(UITableView * _Nonnull)tableView heightForHeaderInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (UITableViewCell * _Nonnull)tableView:(UITableView * _Nonnull)tableView cellForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
- (void)tableView:(UITableView * _Nonnull)tableView didSelectRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
- (CGFloat)tableView:(UITableView * _Nonnull)tableView heightForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
- (void)ImagePickerClicked;
- (nullable instancetype)initWithTableViewStyle:(UITableViewStyle)style OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCollectionViewLayout:(UICollectionViewLayout * _Nonnull)layout OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithScrollView:(UIScrollView * _Nonnull)scrollView OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)decoder OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
@end

















@class UIImagePickerController;
@class UIImage;

@interface ChatMessageVC (SWIFT_EXTENSION(MQTTSDK)) <UIImagePickerControllerDelegate, UINavigationControllerDelegate>
- (void)imagePickerControllerDidCancel:(UIImagePickerController * _Nonnull)picker;
- (void)imagePickerController:(UIImagePickerController * _Nonnull)picker didFinishPickingMediaWithInfo:(NSDictionary<UIImagePickerControllerInfoKey, id> * _Nonnull)info;
- (void)imagePickerController:(UIImagePickerController * _Nonnull)picker pickedImage:(UIImage * _Nullable)pickedImage;
@end



@class UIKeyCommand;
@class UITextView;

@interface ChatMessageVC (SWIFT_EXTENSION(MQTTSDK))
- (BOOL)canPressRightButton SWIFT_WARN_UNUSED_RESULT;
- (void)didPressRightButton:(id _Nullable)sender;
- (void)didPressLeftButton:(id _Nullable)sender;
- (void)didPressReturnKey:(UIKeyCommand * _Nullable)keyCommand;
- (void)textViewDidBeginEditing:(UITextView * _Nonnull)textView;
- (void)textViewDidChange:(UITextView * _Nonnull)textView;
- (void)textViewDidEndEditing:(UITextView * _Nonnull)textView;
@end


SWIFT_CLASS("_TtC7MQTTSDK14ContactDetails")
@interface ContactDetails : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC7MQTTSDK5DBDAO")
@interface DBDAO : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end




SWIFT_CLASS("_TtC7MQTTSDK9DBManager")
@interface DBManager : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end






SWIFT_CLASS("_TtC7MQTTSDK5Email")
@interface Email : BaseModel
@property (nonatomic, copy) NSString * _Nonnull email;
@property (nonatomic) BOOL verified;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithRealm:(RLMRealm * _Nonnull)realm schema:(RLMObjectSchema * _Nonnull)schema OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithValue:(id _Nonnull)value schema:(RLMSchema * _Nonnull)schema OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC7MQTTSDK16EmergencyContact")
@interface EmergencyContact : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC7MQTTSDK9FAQsModal")
@interface FAQsModal : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end




SWIFT_CLASS("_TtC7MQTTSDK6Helper")
@interface Helper : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC7MQTTSDK12LoginService")
@interface LoginService : BaseModel
@property (nonatomic, copy) NSString * _Nullable service;
@property (nonatomic, copy) NSString * _Nullable clientId;
@property (nonatomic) BOOL custom;
@property (nonatomic, copy) NSString * _Nullable serverURL;
@property (nonatomic, copy) NSString * _Nullable tokenPath;
@property (nonatomic, copy) NSString * _Nullable identityPath;
@property (nonatomic, copy) NSString * _Nullable authorizePath;
@property (nonatomic, copy) NSString * _Nullable scope;
@property (nonatomic, copy) NSString * _Nullable buttonLabelText;
@property (nonatomic, copy) NSString * _Nullable buttonLabelColor;
@property (nonatomic, copy) NSString * _Nullable tokenSentVia;
@property (nonatomic, copy) NSString * _Nullable usernameField;
@property (nonatomic) BOOL mergeUsers;
@property (nonatomic, copy) NSString * _Nullable loginStyle;
@property (nonatomic, copy) NSString * _Nullable buttonColor;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithRealm:(RLMRealm * _Nonnull)realm schema:(RLMObjectSchema * _Nonnull)schema OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithValue:(id _Nonnull)value schema:(RLMSchema * _Nonnull)schema OBJC_DESIGNATED_INITIALIZER;
@end








SWIFT_CLASS("_TtC7MQTTSDK8MQTTChat")
@interface MQTTChat : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end









@class CocoaMQTT;
@class CocoaMQTTMessage;

@interface MQTTChat (SWIFT_EXTENSION(MQTTSDK)) <CocoaMQTTDelegate>
- (void)mqtt:(CocoaMQTT * _Nonnull)mqtt didReceive:(SecTrustRef _Nonnull)trust completionHandler:(void (^ _Nonnull)(BOOL))completionHandler;
- (void)mqtt:(CocoaMQTT * _Nonnull)mqtt didConnectAck:(enum CocoaMQTTConnAck)ack;
- (void)mqtt:(CocoaMQTT * _Nonnull)mqtt didStateChangeTo:(enum CocoaMQTTConnState)state;
- (void)mqtt:(CocoaMQTT * _Nonnull)mqtt didPublishMessage:(CocoaMQTTMessage * _Nonnull)message id:(uint16_t)id;
- (void)mqtt:(CocoaMQTT * _Nonnull)mqtt didPublishAck:(uint16_t)id;
- (void)mqtt:(CocoaMQTT * _Nonnull)mqtt didReceiveMessage:(CocoaMQTTMessage * _Nonnull)message id:(uint16_t)id;
- (void)mqtt:(CocoaMQTT * _Nonnull)mqtt didSubscribeTopic:(NSString * _Nonnull)topic;
- (void)mqtt:(CocoaMQTT * _Nonnull)mqtt didUnsubscribeTopic:(NSString * _Nonnull)topic;
- (void)mqttDidPing:(CocoaMQTT * _Nonnull)mqtt;
- (void)mqttDidReceivePong:(CocoaMQTT * _Nonnull)mqtt;
- (void)mqttDidDisconnect:(CocoaMQTT * _Nonnull)mqtt withError:(NSError * _Nullable)err;
@end


SWIFT_CLASS("_TtC7MQTTSDK7Mention")
@interface Mention : BaseModel
@property (nonatomic, copy) NSString * _Nullable username;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithRealm:(RLMRealm * _Nonnull)realm schema:(RLMObjectSchema * _Nonnull)schema OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithValue:(id _Nonnull)value schema:(RLMSchema * _Nonnull)schema OBJC_DESIGNATED_INITIALIZER;
@end



@class Subscription;
@class User;

SWIFT_CLASS("_TtC7MQTTSDK7Message")
@interface Message : BaseModel
@property (nonatomic, strong) Subscription * _Null_unspecified subscription;
@property (nonatomic, copy) NSString * _Nonnull internalType;
@property (nonatomic, copy) NSString * _Nonnull rid;
@property (nonatomic, copy) NSDate * _Nullable createdAt;
@property (nonatomic, copy) NSDate * _Nullable updatedAt;
@property (nonatomic, strong) User * _Nullable user;
@property (nonatomic, copy) NSString * _Nonnull text;
@property (nonatomic) NSInteger isExport;
@property (nonatomic) NSInteger isRead;
@property (nonatomic) BOOL userBlocked;
@property (nonatomic) BOOL pinned;
@property (nonatomic, copy) NSString * _Nonnull alias;
@property (nonatomic, copy) NSString * _Nonnull avatar;
@property (nonatomic, copy) NSString * _Nonnull role;
@property (nonatomic) BOOL temporary;
@property (nonatomic) BOOL groupable;
@property (nonatomic) BOOL markedForDeletion;
@property (nonatomic) NSInteger pinnedPriority;
@property (nonatomic, copy) NSString * _Nonnull jsonResponse;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithRealm:(RLMRealm * _Nonnull)realm schema:(RLMObjectSchema * _Nonnull)schema OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithValue:(id _Nonnull)value schema:(RLMSchema * _Nonnull)schema OBJC_DESIGNATED_INITIALIZER;
@end







@class NSLayoutConstraint;

SWIFT_CLASS("_TtC7MQTTSDK15MessageFilterVC")
@interface MessageFilterVC : UIViewController
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified mainView;
@property (nonatomic, weak) IBOutlet NSLayoutConstraint * _Null_unspecified heightConstant;
- (void)viewDidLoad;
- (void)didReceiveMemoryWarning;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end

@class UIButton;
@class UITapGestureRecognizer;

@interface MessageFilterVC (SWIFT_EXTENSION(MQTTSDK))
- (void)onclickTile:(UIButton * _Nonnull)sender;
- (IBAction)onclickTap:(UITapGestureRecognizer * _Nonnull)sender;
@end

@class UIImageView;

SWIFT_CLASS("_TtC7MQTTSDK19MessageReceiverCell")
@interface MessageReceiverCell : UITableViewCell
@property (nonatomic, weak) IBOutlet UIButton * _Null_unspecified btnImage;
@property (nonatomic, weak) IBOutlet UIImageView * _Null_unspecified imageViewThumb;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified viewChat;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified lblDate;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified lblMessage;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified lblNameTitle;
- (void)awakeFromNib;
- (void)setSelected:(BOOL)selected animated:(BOOL)animated;
- (nonnull instancetype)initWithStyle:(UITableViewCellStyle)style reuseIdentifier:(NSString * _Nullable)reuseIdentifier OBJC_DESIGNATED_INITIALIZER SWIFT_AVAILABILITY(ios,introduced=3.0);
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC7MQTTSDK17MessageSenderCell")
@interface MessageSenderCell : UITableViewCell
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified viewChat;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified lblDate;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified lblMessage;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified lblNameTitle;
- (void)awakeFromNib;
- (void)setSelected:(BOOL)selected animated:(BOOL)animated;
- (nonnull instancetype)initWithStyle:(UITableViewCellStyle)style reuseIdentifier:(NSString * _Nullable)reuseIdentifier OBJC_DESIGNATED_INITIALIZER SWIFT_AVAILABILITY(ios,introduced=3.0);
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC7MQTTSDK10MessageURL")
@interface MessageURL : BaseModel
@property (nonatomic, copy) NSString * _Nullable textDescription;
@property (nonatomic, copy) NSString * _Nullable title;
@property (nonatomic, copy) NSString * _Nullable targetURL;
@property (nonatomic, copy) NSString * _Nullable imageURL;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithRealm:(RLMRealm * _Nonnull)realm schema:(RLMObjectSchema * _Nonnull)schema OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithValue:(id _Nonnull)value schema:(RLMSchema * _Nonnull)schema OBJC_DESIGNATED_INITIALIZER;
@end




SWIFT_CLASS("_TtC7MQTTSDK8ParentVC")
@interface ParentVC : UIViewController
- (void)viewDidLoad;
- (void)didReceiveMemoryWarning;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end

@class UIStoryboardSegue;

SWIFT_CLASS("_TtC7MQTTSDK9MessageVC")
@interface MessageVC : ParentVC
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified IBviewContainerChat;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified IBviewContainerOffice;
@property (nonatomic, weak) IBOutlet UIScrollView * _Null_unspecified IBscrollview;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified IBlblChat;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified IBlblOffice;
@property (nonatomic, weak) IBOutlet UIButton * _Null_unspecified IBbtnChat;
@property (nonatomic, weak) IBOutlet UIButton * _Null_unspecified IBbtnOffice;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified viewContainerMessage;
- (void)viewDidLoad;
- (void)viewWillAppear:(BOOL)animated;
- (void)viewWillDisappear:(BOOL)animated;
- (void)didReceiveMemoryWarning;
- (void)prepareForSegue:(UIStoryboardSegue * _Nonnull)segue sender:(id _Nullable)sender;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end



@class UITabBarController;

@interface MessageVC (SWIFT_EXTENSION(MQTTSDK)) <UITabBarControllerDelegate>
- (void)tabBarController:(UITabBarController * _Nonnull)tabBarController didSelectViewController:(UIViewController * _Nonnull)viewController;
@end






@interface MessageVC (SWIFT_EXTENSION(MQTTSDK)) <UIScrollViewDelegate>
- (void)scrollViewWillBeginDecelerating:(UIScrollView * _Nonnull)scrollView;
- (void)scrollViewDidEndDecelerating:(UIScrollView * _Nonnull)scrollView;
@end




@interface MessageVC (SWIFT_EXTENSION(MQTTSDK))
- (IBAction)onclickChat:(UIButton * _Nonnull)sender;
- (IBAction)onclickOffice:(UIButton * _Nonnull)sender;
- (IBAction)onclickSearch:(UIButton * _Nonnull)sender;
@end






SWIFT_CLASS("_TtC7MQTTSDK14NetworkManager")
@interface NetworkManager : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (void)networkStatusChanged:(NSNotification * _Nonnull)notification;
@end



@interface ParentVC (SWIFT_EXTENSION(MQTTSDK))
- (IBAction)onclickBack:(UIButton * _Nonnull)sender;
- (IBAction)onclickMenu:(UIButton * _Nonnull)sender;
@end


SWIFT_CLASS("_TtC7MQTTSDK10Permission")
@interface Permission : BaseModel
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithRealm:(RLMRealm * _Nonnull)realm schema:(RLMObjectSchema * _Nonnull)schema OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithValue:(id _Nonnull)value schema:(RLMSchema * _Nonnull)schema OBJC_DESIGNATED_INITIALIZER;
@end




SWIFT_CLASS("_TtC7MQTTSDK22PreferredContactMethod")
@interface PreferredContactMethod : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC7MQTTSDK17ReceiverImageCell")
@interface ReceiverImageCell : UITableViewCell
@property (nonatomic, weak) IBOutlet UIButton * _Null_unspecified btnImage;
@property (nonatomic, weak) IBOutlet UIImageView * _Null_unspecified imageViewThumb;
@property (nonatomic, weak) IBOutlet UIImageView * _Null_unspecified imgCell;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified lblDate;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified viewChat;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified lblNameTitle;
- (void)awakeFromNib;
- (void)setSelected:(BOOL)selected animated:(BOOL)animated;
- (nonnull instancetype)initWithStyle:(UITableViewCellStyle)style reuseIdentifier:(NSString * _Nullable)reuseIdentifier OBJC_DESIGNATED_INITIALIZER SWIFT_AVAILABILITY(ios,introduced=3.0);
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC7MQTTSDK15SenderImageCell")
@interface SenderImageCell : UITableViewCell
@property (nonatomic, weak) IBOutlet UIImageView * _Null_unspecified imgCell;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified lblDate;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified lblNameTitle;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified viewChat;
- (void)awakeFromNib;
- (void)setSelected:(BOOL)selected animated:(BOOL)animated;
- (nonnull instancetype)initWithStyle:(UITableViewCellStyle)style reuseIdentifier:(NSString * _Nullable)reuseIdentifier OBJC_DESIGNATED_INITIALIZER SWIFT_AVAILABILITY(ios,introduced=3.0);
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC7MQTTSDK12Subscription")
@interface Subscription : BaseModel
@property (nonatomic, strong) Auth * _Nullable auth;
@property (nonatomic, copy) NSString * _Nonnull privateType;
@property (nonatomic, copy) NSString * _Nonnull rid;
@property (nonatomic, copy) NSString * _Nonnull name;
@property (nonatomic, copy) NSString * _Nonnull fname;
@property (nonatomic) NSInteger unread;
@property (nonatomic) BOOL open;
@property (nonatomic) BOOL alert;
@property (nonatomic) BOOL favorite;
@property (nonatomic, copy) NSDate * _Nullable createdAt;
@property (nonatomic, copy) NSDate * _Nullable lastSeen;
@property (nonatomic, copy) NSString * _Nullable roomTopic;
@property (nonatomic, copy) NSString * _Nullable roomDescription;
@property (nonatomic) BOOL roomReadOnly;
@property (nonatomic, copy) NSString * _Nullable roomOwnerId;
@property (nonatomic, copy) NSString * _Nullable otherUserId;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithRealm:(RLMRealm * _Nonnull)realm schema:(RLMObjectSchema * _Nonnull)schema OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithValue:(id _Nonnull)value schema:(RLMSchema * _Nonnull)schema OBJC_DESIGNATED_INITIALIZER;
@end









@class CADisplayLink;

SWIFT_CLASS("_TtC7MQTTSDK10TypingCell")
@interface TypingCell : UITableViewHeaderFooterView
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified viewWave;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified view2;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified view1;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified view3;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified view4;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified view5;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified lblName;
@property (nonatomic, weak) IBOutlet UIButton * _Null_unspecified btnImage;
@property (nonatomic, weak) IBOutlet UIImageView * _Null_unspecified imageViewThumb;
@property (nonatomic, weak) IBOutlet UIButton * _Null_unspecified v2btnImage1;
@property (nonatomic, weak) IBOutlet UIImageView * _Null_unspecified v2imageViewThumb1;
@property (nonatomic, weak) IBOutlet UIButton * _Null_unspecified v2btnImage2;
@property (nonatomic, weak) IBOutlet UIImageView * _Null_unspecified v2imageViewThumb2;
@property (nonatomic, weak) IBOutlet UIButton * _Null_unspecified v3btnImage1;
@property (nonatomic, weak) IBOutlet UIImageView * _Null_unspecified v3imageViewThumb1;
@property (nonatomic, weak) IBOutlet UIButton * _Null_unspecified v3btnImage2;
@property (nonatomic, weak) IBOutlet UIImageView * _Null_unspecified v3imageViewThumb2;
@property (nonatomic, weak) IBOutlet UIButton * _Null_unspecified v3btnImage3;
@property (nonatomic, weak) IBOutlet UIImageView * _Null_unspecified v3imageViewThumb3;
@property (nonatomic, weak) IBOutlet UIButton * _Null_unspecified v4btnImage1;
@property (nonatomic, weak) IBOutlet UIImageView * _Null_unspecified v4imageViewThumb1;
@property (nonatomic, weak) IBOutlet UIButton * _Null_unspecified v4btnImage2;
@property (nonatomic, weak) IBOutlet UIImageView * _Null_unspecified v4imageViewThumb2;
@property (nonatomic, weak) IBOutlet UIButton * _Null_unspecified v4btnImage3;
@property (nonatomic, weak) IBOutlet UIImageView * _Null_unspecified v4imageViewThumb3;
@property (nonatomic, weak) IBOutlet UIButton * _Null_unspecified v4btnImage4;
@property (nonatomic, weak) IBOutlet UIImageView * _Null_unspecified v4imageViewThumb4;
@property (nonatomic, weak) IBOutlet UIButton * _Null_unspecified v5btnImage1;
@property (nonatomic, weak) IBOutlet UIImageView * _Null_unspecified v5imageViewThumb1;
@property (nonatomic, weak) IBOutlet UIButton * _Null_unspecified v5btnImage2;
@property (nonatomic, weak) IBOutlet UIImageView * _Null_unspecified v5imageViewThumb2;
@property (nonatomic, weak) IBOutlet UIButton * _Null_unspecified v5btnImage3;
@property (nonatomic, weak) IBOutlet UIImageView * _Null_unspecified v5imageViewThumb3;
@property (nonatomic, weak) IBOutlet UIButton * _Null_unspecified v5btnImage4;
@property (nonatomic, weak) IBOutlet UIImageView * _Null_unspecified v5imageViewThumb4;
@property (nonatomic, weak) IBOutlet UIButton * _Null_unspecified v5btnImage5;
@property (nonatomic, weak) IBOutlet UIImageView * _Null_unspecified v5imageViewThumb5;
- (void)awakeFromNib;
/// Handle the display link timer.
/// \param displayLink The display link.
///
- (void)handleDisplayLink:(CADisplayLink * _Nonnull)displayLink;
- (nonnull instancetype)initWithReuseIdentifier:(NSString * _Nullable)reuseIdentifier OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end




























@interface UITextField (SWIFT_EXTENSION(MQTTSDK))
@property (nonatomic, strong) UIColor * _Nullable placeHolderColor;
@end






@interface UIViewController (SWIFT_EXTENSION(MQTTSDK))
- (void)keyboardWillShow:(NSNotification * _Nonnull)notification;
- (void)keyboardWillHide:(NSNotification * _Nonnull)notification;
@end


SWIFT_CLASS("_TtC7MQTTSDK4User")
@interface User : BaseModel
@property (nonatomic, copy) NSString * _Nullable username;
@property (nonatomic, copy) NSString * _Nullable name;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithRealm:(RLMRealm * _Nonnull)realm schema:(RLMObjectSchema * _Nonnull)schema OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithValue:(id _Nonnull)value schema:(RLMSchema * _Nonnull)schema OBJC_DESIGNATED_INITIALIZER;
@end










SWIFT_CLASS("_TtC7MQTTSDK15UserInformarion")
@interface UserInformarion : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC7MQTTSDK12UtilityClass")
@interface UtilityClass : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC7MQTTSDK19ViewNoDataFoundCell")
@interface ViewNoDataFoundCell : UITableViewCell
- (void)awakeFromNib;
- (void)setSelected:(BOOL)selected animated:(BOOL)animated;
- (nonnull instancetype)initWithStyle:(UITableViewCellStyle)style reuseIdentifier:(NSString * _Nullable)reuseIdentifier OBJC_DESIGNATED_INITIALIZER SWIFT_AVAILABILITY(ios,introduced=3.0);
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC7MQTTSDK13twoTypingCell")
@interface twoTypingCell : UITableViewCell
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified lblName;
@property (nonatomic, weak) IBOutlet UIButton * _Null_unspecified btnImage;
@property (nonatomic, weak) IBOutlet UIImageView * _Null_unspecified imageViewThumb;
@property (nonatomic, weak) IBOutlet UIButton * _Null_unspecified btnImage2;
@property (nonatomic, weak) IBOutlet UIImageView * _Null_unspecified imageViewThumb2;
- (void)awakeFromNib;
- (void)setSelected:(BOOL)selected animated:(BOOL)animated;
- (nonnull instancetype)initWithStyle:(UITableViewCellStyle)style reuseIdentifier:(NSString * _Nullable)reuseIdentifier OBJC_DESIGNATED_INITIALIZER SWIFT_AVAILABILITY(ios,introduced=3.0);
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end

#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#pragma clang diagnostic pop
